### ISSUE TITLE
Please change the name of this plugin

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder.line_profiler#1]
This should be named `line_profiler`, not `profiler`, to avoid confusions and collusions with our current `profiler` plugin.

@goanpeca, I hope you haven't created the PyPi package yet.

**Comment by goanpeca** [comment]
Dont worry.. even if it was created you can change the names and erase them (from pypi)....

I should not clash because of the namespacing, but line profiler was getting too long....

**Comment by ccordoba12** [comment]
But I really prefer it because we already have a `profiler` plugin, as I said.

Besides, `line_profiler` is well known in several circles, so please change it.

**Comment by goanpeca** [comment]
I did not imply I was not going to change it :-) :+1:

**Comment by ccordoba12** [comment]
Ok, sorry for the confusion :-)

**Comment by goanpeca** [comment]
hmmmmm ok... so some othe roptions

@ccordoba12 
`spyplugins.ui.lineprofiler`
`spyplugins.ui.lprofiler`
`spyplugins.ui.line_profiler`  <- looks ugly :-(

**Comment by ccordoba12** [comment]
Please leave it as line_profiler. I know it's not that good, but we 
already have things like jupyter_core in the community, so I don't see a 
problem with that name.

**Comment by goanpeca** [comment]
:+1: (but it looks ugly!)

**Comment by ccordoba12** [comment]
I know, but at least is clear enough :-)

**Comment by ccordoba12** [comment]
Thanks for the change.

**Comment by ccordoba12** [comment]
By the way, do plugins **need** to be named

```
spyplugins.{ui/io}.foo
```

instead of just

```
spyplugins.foo
```

?

I mean, at the end, `ui` (or `io`) is part of the plugin structure, isn't it?

**Comment by goanpeca** [comment]
I guess we could... ;-)  @Nodd ?

**Comment by Nodd** [comment]
I don't know what has been decided in the last two months ! :smile: 
I just think that if some plugins have io or ui prefix, then all of them should have it.
(also, too late but indeed line_profiler is better. That's the name of the tool)

**Comment by goanpeca** [comment]
The last meeting we had with @blink1073 and @ccordoba12 we thought that to have some order on the plugins... at least the ones that are somehow maintained by the "Spyder development team" and in the spirit of having a shorter name to have:

instead of  `spyplugins.ui.line_profiler`, just `spyder.line_profiler`.

It is worth noting that this would be the name of the package (for conda/pip installation purposes.. `pip/conda install spyder.line_profiler`). The ui and io namespaces wil remain `spyplugins.ui` and `spyplugins.io`

What do you think @Nodd ?

**Comment by Nodd** [comment]
So if I understand correctly, the name of the package itself is different from the directory structure inside the package ? I agree that it makes sense, `spyplugins.ui.*` is ugly for a name.

**Comment by goanpeca** [comment]
Great then it is settled :-) :+1: with your blessings

**Comment by goanpeca** [comment]
@ccordoba12 @blink1073 @Nodd @SylvainCorlay 

Just to double check, the idea is to have packages name like

`spyder.line-profiler`
`spyder.memory-profiler`

or

`spyder.line_profiler`
`spyder.memory_profiler`

I know that the original package is `line_profiler`, but the `-` looks better. I forgot what was the final decision... :s

so that installation could be

`pip install spyder.line-profiler`
or
`conda install spyder.line-profiler -c spyder-ide`

**Comment by blink1073** [comment]
It's called `line_profiler` on PyPI, I'd say stick with that.

**Comment by blink1073** [comment]
https://pypi.python.org/pypi/line_profiler/

**Comment by goanpeca** [comment]
Ok :+1:

**Comment by ccordoba12** [comment]
Yep, +1 from me too to what @blink1073 suggested :-)
