### ISSUE TITLE
Update plugin to Spyder v4

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder.line_profiler#26]
Currently the plugin fails in Spyder v4 with:
```
    from spyder.plugins.configdialog import PluginConfigPage
ImportError: cannot import name 'PluginConfigPage'
```

**Comment by Landau1908** [comment]
I meet the error, too.

**Comment by jcox-nd** [comment]
Did PluginConfigPage simply get renamed or relocated in Spyder 4.0? By doing a search of spyder origin/master, I find:
from spyder.api.preferences import PluginConfigPage

So what happens if you just change all references from:
'from spyder.plugins.configdialog import PluginConfigPage' -> from spyder.api.preferences import PluginConfigPage

Does it work?

**Comment by ccordoba12** [comment]
@jcox-nd, that's almost the right fix. You need to do something like this:

```python
try:
    from spyder.plugins.configdialog import PluginConfigPage
except ImportError:
    from spyder.api.preferences import PluginConfigPage
```

to make the plugin compatible with both Spyder 3 and 4.

Please make a PR with that fix so we can release a be version.
