### ISSUE TITLE
Profiler changes working directory

### ISSUE THREAD

**Issue by ianbstewart** [spyder-ide/spyder.line_profiler#28]
I am trying to profile a Python file in a subdirectory, root/A/B/test.py. The script has to be run from the root directory in order for the imports to work. When I try to run the profiler in Spyder, I get an import error because the profiler has changed to working directory to root/A/B when it should still be root/. How can I prevent the profiler from changing the working directory?

**Comment by CAM-Gerlach** [comment]
Just to confirm, you are using the ``spyder-line-profiler`` plugin and not the built-in Spyder profiler (which is already well known to have this issue; see spyder-ide/spyder#1110 , and I'll hopefully get to solving it in Spyder 4)? Active maintenance on this plugin (and most others) is currently paused to focus on the Spyder 4 release, and should be resumed in early 2019, although if you'd like to help fix it yourself (its pure Python, just like your own code) we'd be happy to review a PR.

**Comment by Nodd** [comment]
spyder-line-profiler is an adaptation of the built-in Spyder profiler, so the bug has been ported too. If one is fixed, the other one should be easy to port.

**Comment by ianbstewart** [comment]
@CAM-Gerlach yes, I am using the spyder-line-profiler. To be honest this seems like a pretty big issue to postpone, because I imagine that many developers have similarly complicated code (relative imports, etc.) that they want to profile. I don't have time to fix it now but if I find a workaround in the future I will let you know.

**Comment by CAM-Gerlach** [comment]
Ah, thanks for the insight from an old hand here, @Nodd . I'm the new guy, in case you couldn't tell, heh

At least as originally conceived, the work currently planned to address spyder-ide/spyder#1110 primarily relates to integrating the profiler with the Run Settings GUI, or creating some sort of dedicated GUI for it, rather than fixing a "bug" that is really more a deliberate, if rather baffling design choice. However, getting something rudimentary in place to just use the current working directory vs. just using the file directory shouldn't be terribly complicated, I wouldn't think. However, @Nodd clearly has far more expertise and experience than I in this matter.

> To be honest this seems like a pretty big issue to postpone, because I imagine that many developers have similarly complicated code (relative imports, etc.) that they want to profile. 

@ianbstewart It's less a deliberate postponement of this specific work, and more a deliberate temporary freeze on the plugins until Spyder 4 which will greatly overhaul the whole system (for the better). As a volunteer, community-supported project we have relatively limited developer time, not to mention nearly a dozen other plugins besides. However, we're more than happy to review a PR from you.

>  I imagine that many developers have similarly complicated code (relative imports, etc.) that they want to profile. 

Indeed, this was an issue for my own code, which I why I want to work on it for Spyder 4 at some point.

> I don't have time to fix it now but if I find a workaround in the future I will let you know.

I got around it by just uncommenting absolute paths for use with the profiler, and one could also do it by other means like a cwd command or other such tricks. An ugly hack, but should be usable.

**Comment by cdfredrick** [comment]
It is not the working directory that truly matters for imports but [sys.path](https://docs.python.org/3/library/sys.html#sys.path). Python only searches the directories in its sys.path variable for modules, so if the current directory is not in the path then imports from the current directory are not going to work. On initialization Python only prepends a generalized "current directory" (represented as an empty string) to the path when it is run interactively, not when it is called to run a script such as in line_profiler. For these other cases, Python adds the directory of the file that the interpreter was called with. Since almost all of Spyder is interactive IPython consoles you may not have noticed this.

As for a solution to get your desired behavior, just use Spyder's PYTHONPATH manager. Under "Tools" in the top menu select "PYTHONPATH manager" and then add your root directory. The directories in [PYTHONPATH](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) are inserted into sys.path at the top of the list directly after that of the initialized directory.

**Comment by ccordoba12** [comment]
@cdfredrick, would you say this can be closed, per your advice?

**Comment by cdfredrick** [comment]
Yes, for setting import locations without having to change or add absolute paths to one's code, I think the PYTHONPATH manager is the way to go. The manager is already integrated into spyder-line-profiler when using the shortcut "Shift+f10" or when selecting "Profile line by line" from the run menu, and with #30 that behavior is also brought to the profiler when it is started from the widget. 

For cases where the working directory does need to be set, such as interacting with files, I believe #30 also takes care of that by reading the desired working directory from the run configuration.

**Comment by ccordoba12** [comment]
Thanks @cdfredrick! Closing then.
