### ISSUE TITLE
Adapt colors to dark mode

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder.line_profiler#50]
I'm probably the only one still using this plugin, but I saw that the colors do not accurately translate to the Spyder dark mode. Maybe this can be fixed? Or is it something in Qt?

**Comment by ccordoba12** [comment]
Hey @skjerns, we're planning to improve a complete color palette for the dark and light modes in Spyder 5, so you'll be able to pick a nice color from it to use it here.

**Comment by jitseniesen** [comment]
At the moment, every function is assigned an arbitrary colour, and then the lines in a function get that colour, with lines in which more time is spent relative to the other lines in the same function getting a brighter colour. So the hue indicates that lines in the same functions are compared to each other, but not to lines in other functions.

I can see various options for adapting the Spyder palette:
1. Choose a couple of colours from the palette, say the colours used in the variable explorer, and cycle through those colours. The first function gets the first colour, with brightness indicating how much time is spent in each line relative to the total time in the function, the second function gets the second colour, and so on. This is the closest to the current UI but it may not be obvious to users what the colours mean (it was not obvious to me).
2. Choose one colour (say the blue which indicates "found" text in the editor) and use this for all lines, with brightness indicating how much time is spent in each line relative to the total time in the function. This may be confusing, because lines with different time spent in them may be coloured exactly the same.
3. Choose one colour and use this for all lines, with brightness indicating how much time is spent in each line relative to the total time spent in all the functions. This is a departure of the current behaviour but it will restrict us to the core colours in the palette.

@skjerns Since you are (or were) still using the plugin, what do you think?

**Comment by jitseniesen** [comment]
Going for option 1 since this is closest to the status quo.

**Comment by skjerns** [comment]
Sorry for not replying, it got lost in my emails. 

I'd say having a consistent color across all functions would be best. Sometimes you want to compare times between two functions and then having different colors makes it difficult to visually compare the shades.

What is the reasoning for assigning each function its own color? Does it have any case where it is of advantage?
