### ISSUE TITLE
unusable on spyder 5.1

### ISSUE THREAD

**Issue by Li-xy-lucky** [spyder-ide/spyder.line_profiler#64]
I have alreadey install the line profiler, and my python is 3.9 and spyder is 5.1. The information in console tell me that the profiler has been installed. But I couldn't  find the Run line profiler under Run, and the decorator @profile is not readable.  I think maybe this plugin is not compatible with Spyder 5. But I really really want to use it. Could you please update it?

**Comment by dalthviz** [comment]
Hi @Li-xy-lucky you need to use [`spyder >= 5.2`](https://github.com/spyder-ide/spyder-line-profiler/blob/cb4e4ef40b5b49d07f4974c1f8a7366d75fbe0a3/setup.py#L41) to install the plugin version compatible with Spyder 5 (`spyder-line-profiler 0.3.0`). Could you please update Spyder to be >=5.2.0 <=5.3.1 and try again?

Let us know if that helps!

Edit: Specify Spyder version to update since seems like the plugin is not working with Spyder 5.3.2. See #65

**Comment by jitseniesen** [comment]
Closing because we did not get any reply.
