### ISSUE TITLE
Use selected python interpreter/environment instead of default (same as Spyder) when profiling

### ISSUE THREAD

**Issue by rhkarls** [spyder-ide/spyder.line_profiler#67]
When running the plugin and having a different environment than Spyder's active it will not actually use that environment in the profiling. This will often lead to import errors or using different versions of installed packages.

I suppose this issue is related to what is mentioned here: https://github.com/spyder-ide/spyder-unittest/issues/177

Apologies if this is a duplicate of #5

**Comment by jitseniesen** [comment]
I think it is the same issue as #5 but your description is clearer and there is not much of relevant there so I will close that issue.

The closest equivalent issue for the unittest plugin is spyder-ide/spyder-unittest#65. But I think it may be easier to compare with the profiler in Spyder proper, where I think this was fixed in commit spyder-ide/spyder@bdea2c0c688173c61e44ece92f0519bd188290a1. That is a one-line change so maybe it is also easy to fix for the line-profiler plugin.

**Comment by ccordoba12** [comment]
Yep, the idea is to use the `executable` option of the Main interpreter plugin to get the current Python interpreter set by users in Preferences.

**Comment by battaglia01** [comment]
Does there currently exist any way around this problem? Would love to use this plugin, but every time I try to run it I get errors saying that various modules don't exist and etc. I'm not even sure which version of python it thinks that it's using or how to determine that or change it. I'm running spyder in conda; is there some way I can get this plugin to use the correct version of Python without having to e.g. change my PATH system-wide?
