### ISSUE TITLE
Latest conda install issue

### ISSUE THREAD

**Issue by jtdbod** [spyder-ide/spyder.line_profiler#69]
Running into issue installing via conda on Windows 10. 
Getting the following error when running install via `conda install spyder-line-profiler -c conda-forge`:
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

Spyder is freshly installed in its own environment.
Conda 23.1.0
Python 3.10.9
Spyder 5.4.2

**Comment by dalthviz** [comment]
Hi @jtdbod could it be possible for you to install constraining `spyder-line-profiler` to be 0.3.1 in your env (something like `conda install -c conda-forge spyder-line-profiler=0.3.1`)? I tried running `conda create -n line-profiler -c conda-forge python=3.10.9 spyder=5.4.2 spyder-line-profiler=0.3.1` locally but that command solves the env correctly for me and prompts me to install the packages 🤔 

Any other info in order to better understand what could be happening is greatly appreciated!

**Comment by jtdbod** [comment]
Running into the same issue when trying to create a new env with constrained versions. It looks like the issue is related to accessing conda-forge specifically because I get the same error for all packages I try to install via that channel. Unrelated to spyder-line-profiler. Thanks!

**Comment by dalthviz** [comment]
Thanks for the new info @jtdbod ! I will close then this as invalid. However, if you experience any other problem let us know :+1:
