### ISSUE TITLE
Menu item doesn't appear

### ISSUE THREAD

**Issue by igurin-invn** [spyder-ide/spyder.line_profiler#70]
I installed `spyder-line-profiler` using `conda`. I had to manually set the version to 0.3.0.

```
The following NEW packages will be INSTALLED:

  line_profiler      pkgs/main/win-64::line_profiler-2.1.2-py310h2bbff1b_0 None
  spyder-line-profi~ spyder-ide/noarch::spyder-line-profiler-0.3.0-pyh6c4a22f_0 None
```

When I open a fresh instance of Spyder (v5.3.3), I don't see the plugin in the `Panes` menu.

**Comment by dalthviz** [comment]
Hi @igurin-invn to use the plugin with Spyder 5.3.2 or higher you need to install spyder-line-profiler 0.3.1 (that release fixes a compatibility issue due to changes done in Spyder 5.3.2). However, could it be that you had to manually set the version to 0.3.0 due to facing a similar env solving error as the one reported at https://github.com/spyder-ide/spyder-line-profiler/issues/69 ?

Let us know!

**Comment by igurin-invn** [comment]
I see. Version 0.3.0 was actually just carelessness on my part. The default version in this particular environment (which is otherwise my most up-to-date) was 0.2.1.

Trying to install version 0.3.1 did give the error reported at #69.

When using `conda-forge`, the installation succeeds. Thanks!

**Comment by igurin-invn** [comment]
I still get a `NameError` when trying to `@profile` a function, though. Do I need to import anything? I guess this should be a new issue.

**Comment by jitseniesen** [comment]
@igurin-invn No, you don't need to import anything. However, you need to use the "Run line profiler" item under the "Run" menu to run and profile your script. If you use the normal "Run" command, you will get a NameError (I think).
